description: $description
version: "${version}"

api-version: "26.2"
load: POSTWORLD

main: top.neila.slimevanilla.core.Slimevanilla
name: Slimevanilla
author: Neila

dependencies:
  server:
    Slimefun:
      load: BEFORE # Defaults to OMIT
      required: true # Defaults to true
      join-classpath: true # Defaults to true
