[versions]
kotlin = "2.4.20-Beta2"

paper-api = "26.2.build.+"
slimefun = "RC-37"
minecraft = "26.2"

shadow = "9.6.1"
run-task = "3.0.2"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
slimefun = { module = "com.github.Slimefun:Slimefun4", version.ref = "slimefun" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
